name: maestro
description: "Music player"

publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

#-------------------- PACKAGES --------------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_svg: ^2.0.10+1
  gradient_widgets_plus: ^1.0.0
  flutter_native_splash: ^2.3.2
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dartz: ^0.10.1

  # Icons
  cupertino_icons: ^1.0.8
  bootstrap_icons: ^1.11.3

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  firebase_app_check: ^0.3.0+1
  googleapis_auth: ^1.6.0

#-------------------- ./ PACKAGES END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Utility Packages
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  intl_translation: ^0.20.0
  intl_utils: ^2.8.7
  build_runner: ^2.1.7
  build_config: ^1.0.0
  build_version: ^2.1.1

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/generated/l10n

flutter:
  uses-material-design: true
  generate: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/vectors/
    - assets/sounds/

  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/maestro-logo.png
