name: maestro
description: "Music player"

publish_to: 'none'

version: 1.0.13+114438

environment:
  sdk: '>=3.4.1 <4.0.0'

#-------------------- PACKAGES --------------------#

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  path: ^1.9.0
  logger: ^2.5.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.0.17
  gradient_widgets_plus: ^1.0.0
  flutter_native_splash: ^2.4.1
  cached_network_image: ^3.4.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  just_audio: ^0.9.46
  image_picker: ^1.1.2
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  timeago: ^3.7.0
  photo_manager: ^3.6.4
  equatable: ^2.0.7
  file_picker: ^9.0.0
  share_plus: ^10.1.4
  device_info_plus: ^11.3.0
  shared_preferences: ^2.5.2
  flutter_chrome_cast: ^0.0.11
  flutter_staggered_grid_view: ^0.7.0
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  android_intent_plus: ^5.3.0
  waterfall_flow: ^3.1.1
  smooth_page_indicator: ^1.2.1
  package_info_plus: ^8.3.0
  uuid: ^4.5.1
  audio_service: ^0.18.17
  audio_session: ^0.1.25
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.27.7
  audiotags: ^1.4.3
  flutter_background: ^1.3.0+1
  palette_generator: ^0.3.3+6

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  bootstrap_icons: ^1.11.3
  fluentui_system_icons: ^1.1.270
  icons_plus: ^5.0.0
  marquee: ^2.3.0
  evil_icons_flutter: ^0.5.0
  carbon_icons: ^0.0.1+2
  typicons_flutter: ^0.5.0
  flutter_phosphor_icons: ^0.0.1+6
  remixicon: ^1.3.0
  antdesign_icons: ^0.0.3
  ionicons: ^0.2.2
  weather_icons: ^3.0.0
  mono_icons: ^1.0.0+2
  jam_icons: ^0.0.1
  heroicons: ^0.11.0
  flutter_tabler_icons: ^1.43.0
  lucide_icons: ^0.257.0
  iconify_flutter_plus: ^1.0.4
  feather_icons: ^1.2.0
  majesticons: ^1.0.1
  simple_icons: ^14.6.1
  hugeicons: ^0.0.7
  iconoir_flutter: ^7.10.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.2
  firebase_app_check: ^0.3.2+2
  googleapis_auth: ^1.6.0
  sign_in_with_apple: ^6.1.1

#-------------------- ./ PACKAGES END --------------------#

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Utility Packages
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  intl_translation: ^0.20.1
  intl_utils: ^2.8.7
  build_runner: ^2.4.14
  build_config: ^1.1.2
  build_version: ^2.1.1

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/generated/l10n

flutter:
  uses-material-design: true
  generate: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/images/
    - assets/icons/flags/
    - assets/vectors/
    - assets/vectors/flags/
    - assets/sounds/

  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica-Light.otf
          weight: 300
        - asset: assets/fonts/Helvetica/Helvetica-Regular.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Helvetica/Helvetica-Italic.otf
          weight: 500
        - asset: assets/fonts/Helvetica/Helvetica-Bold.otf
          weight: 800
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Regular.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi/Satoshi-Bold.ttf
          weight: 800
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/Coolvetica/Coolvetica-Italic.otf
          style: italic
        - asset: assets/fonts/Coolvetica/Coolvetica-Regular.otf
          weight: 400
    - family: Interstate
      fonts:
        - asset: assets/fonts/Interstate/Interstate-Thin-Italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Interstate/Interstate-Extra-Light-Italic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Interstate/Interstate-Light-Cond.ttf
          weight: 300
        - asset: assets/fonts/Interstate/Interstate-Regular.ttf
          weight: 400
        - asset: assets/fonts/Interstate/Interstate-Regular-Comp.ttf
          weight: 400
        - asset: assets/fonts/Interstate/Interstate-Regular-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Interstate/Interstate-Bold-Cond.ttf
          weight: 700
        - asset: assets/fonts/Interstate/Interstate-Bold.ttf
          weight: 700
        - asset: assets/fonts/Interstate/Interstate-Bold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Interstate/Interstate-Black-Comp.ttf
          weight: 900
        - asset: assets/fonts/Interstate/Interstate-Black-Cond.ttf
          weight: 900
        - asset: assets/fonts/Interstate/Interstate-Ultra-Black-Comp.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/maestro-logo.png
